//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Account struct {
	ID          *int32 `sql:"primary_key"`
	OwnerID     int32
	Name        string
	DisplayName string
	IsSystem    int32
	IsWorld     int32
	IsGroup     int32
	TypeID      int32
	GroupID     *int32
}
