//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Account struct {
	ID          *int32 `sql:"primary_key"`
	Created     string
	Name        string
	DisplayName string
	OwnerID     int32
	IsSystem    int32
	IsWorld     int32
	IsCredit    int32
}
