//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Balance struct {
	Timestamp   string `sql:"primary_key"`
	AccountID   *int32 `sql:"primary_key"`
	Value       string
	Delta       *string
	Comment     *string
	IsComputed  int32
	OperationID *int32
}
