//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Operation struct {
	ID          *int32 `sql:"primary_key"`
	CreatedOn   string
	ModifiedOn  string
	CreatedByID int32
	Description string
	TypeID      *int32
	Details     *string
	CategoryID  *int32
}
