//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Transaction struct {
	ID          *int32 `sql:"primary_key"`
	FromID      int32
	ToID        int32
	Amount      int32
	OperationID *int32
}
