//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Account = newAccountTable("", "account", "")

type accountTable struct {
	sqlite.Table

	//Columns
	ID          sqlite.ColumnInteger
	OwnerID     sqlite.ColumnInteger
	Name        sqlite.ColumnString
	DisplayName sqlite.ColumnString
	IsDefault   sqlite.ColumnInteger
	IsWorld     sqlite.ColumnInteger
	IsSystem    sqlite.ColumnInteger
	IsGroup     sqlite.ColumnInteger
	TypeID      sqlite.ColumnInteger
	GroupID     sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type AccountTable struct {
	accountTable

	EXCLUDED accountTable
}

// AS creates new AccountTable with assigned alias
func (a AccountTable) AS(alias string) *AccountTable {
	return newAccountTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AccountTable with assigned schema name
func (a AccountTable) FromSchema(schemaName string) *AccountTable {
	return newAccountTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AccountTable with assigned table prefix
func (a AccountTable) WithPrefix(prefix string) *AccountTable {
	return newAccountTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AccountTable with assigned table suffix
func (a AccountTable) WithSuffix(suffix string) *AccountTable {
	return newAccountTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAccountTable(schemaName, tableName, alias string) *AccountTable {
	return &AccountTable{
		accountTable: newAccountTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newAccountTableImpl("", "excluded", ""),
	}
}

func newAccountTableImpl(schemaName, tableName, alias string) accountTable {
	var (
		IDColumn          = sqlite.IntegerColumn("id")
		OwnerIDColumn     = sqlite.IntegerColumn("owner_id")
		NameColumn        = sqlite.StringColumn("name")
		DisplayNameColumn = sqlite.StringColumn("display_name")
		IsDefaultColumn   = sqlite.IntegerColumn("is_default")
		IsWorldColumn     = sqlite.IntegerColumn("is_world")
		IsSystemColumn    = sqlite.IntegerColumn("is_system")
		IsGroupColumn     = sqlite.IntegerColumn("is_group")
		TypeIDColumn      = sqlite.IntegerColumn("type_id")
		GroupIDColumn     = sqlite.IntegerColumn("group_id")
		allColumns        = sqlite.ColumnList{IDColumn, OwnerIDColumn, NameColumn, DisplayNameColumn, IsDefaultColumn, IsWorldColumn, IsSystemColumn, IsGroupColumn, TypeIDColumn, GroupIDColumn}
		mutableColumns    = sqlite.ColumnList{OwnerIDColumn, NameColumn, DisplayNameColumn, IsDefaultColumn, IsWorldColumn, IsSystemColumn, IsGroupColumn, TypeIDColumn, GroupIDColumn}
	)

	return accountTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		OwnerID:     OwnerIDColumn,
		Name:        NameColumn,
		DisplayName: DisplayNameColumn,
		IsDefault:   IsDefaultColumn,
		IsWorld:     IsWorldColumn,
		IsSystem:    IsSystemColumn,
		IsGroup:     IsGroupColumn,
		TypeID:      TypeIDColumn,
		GroupID:     GroupIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
