//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var User = newUserTable("", "user", "")

type userTable struct {
	sqlite.Table

	//Columns
	ID          sqlite.ColumnInteger
	Name        sqlite.ColumnString
	DisplayName sqlite.ColumnString
	IsAdmin     sqlite.ColumnInteger
	Password    sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type UserTable struct {
	userTable

	EXCLUDED userTable
}

// AS creates new UserTable with assigned alias
func (a UserTable) AS(alias string) *UserTable {
	return newUserTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserTable with assigned schema name
func (a UserTable) FromSchema(schemaName string) *UserTable {
	return newUserTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserTable with assigned table prefix
func (a UserTable) WithPrefix(prefix string) *UserTable {
	return newUserTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserTable with assigned table suffix
func (a UserTable) WithSuffix(suffix string) *UserTable {
	return newUserTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserTable(schemaName, tableName, alias string) *UserTable {
	return &UserTable{
		userTable: newUserTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newUserTableImpl("", "excluded", ""),
	}
}

func newUserTableImpl(schemaName, tableName, alias string) userTable {
	var (
		IDColumn          = sqlite.IntegerColumn("id")
		NameColumn        = sqlite.StringColumn("name")
		DisplayNameColumn = sqlite.StringColumn("display_name")
		IsAdminColumn     = sqlite.IntegerColumn("is_admin")
		PasswordColumn    = sqlite.StringColumn("password")
		allColumns        = sqlite.ColumnList{IDColumn, NameColumn, DisplayNameColumn, IsAdminColumn, PasswordColumn}
		mutableColumns    = sqlite.ColumnList{NameColumn, DisplayNameColumn, IsAdminColumn, PasswordColumn}
	)

	return userTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		DisplayName: DisplayNameColumn,
		IsAdmin:     IsAdminColumn,
		Password:    PasswordColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
